FROM node:19.4.0-alpine3.17 as dev

WORKDIR '/app'

COPY package.json .
RUN apk update && apk upgrade && npm install && npm install -g npm-check-updates && ncu --upgrade && rm -vrf /var/cache/apk/*
COPY . .

CMD ["npm", "run", "start"]
